# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-07 00:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracware', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trac',
            name='trac_type',
            field=models.CharField(choices=[('Like', 'Like'), ('Star', 'Star'), ('Watch', 'Watch'), ('Follow', 'Follow'), ('Bookmark', 'Bookmark')], max_length=20),
        ),
    ]
